# Generated by Django 4.0.1 on 2022-02-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blimpUP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blimp',
            name='description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='blimp',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
