# Generated by Django 4.0.1 on 2022-02-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blimpUP', '0002_alter_blimp_description_alter_blimp_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blimp',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
