# Generated by Django 4.0.1 on 2022-02-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blimpUP', '0004_alter_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges', models.IntegerField(default=1)),
                ('blimp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_charges', to='blimpUP.blimp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_charges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
