# Generated by Django 4.0.1 on 2022-02-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blimpUP', '0005_reviewcharges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewCharges',
            new_name='ReviewCharge',
        ),
    ]
