# Generated by Django 4.0.1 on 2022-02-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blimpUP', '0006_rename_reviewcharges_reviewcharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcharge',
            name='charges',
        ),
    ]
