# Generated by Django 4.0.1 on 2022-02-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blimpUP', '0007_remove_reviewcharge_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='blimp',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='blimp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='blimpUP.blimp'),
        ),
    ]
