# Generated by Django 4.0.1 on 2022-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blimpUP', '0008_blimp_average_rating_alter_passenger_blimp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blimp',
            name='latitude',
            field=models.TextField(default=0, max_length=80),
        ),
        migrations.AddField(
            model_name='blimp',
            name='longitude',
            field=models.TextField(default=0, max_length=80),
        ),
    ]
