# Generated by Django 4.0.1 on 2022-03-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blimpUP', '0009_blimp_latitude_blimp_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blimp',
            name='latitude',
            field=models.TextField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='blimp',
            name='longitude',
            field=models.TextField(default=0, max_length=40),
        ),
    ]
